import epimine
import os
import numpy as np
from tqdm import tqdm

gold_episodes = {
    "2021_atlanta_shootings": '{subject: "Long", action: "fired", object: "shots", time: "March 16th after 4:50 pm", location: "Youngs Asian Massage"}	{subject: "Police", action: "respond", object: "shooting", time: "March 16th after 5:47 pm", location: "Gold Massage Spa"}	{subject: "Long\'s family", action: "identifed", object: "murder suspect Long", time: "Tuesday March 16th", location: "Morristown, Tennessee"}	{subject: "Long", action: "charged", object: "murder", time: "Wednesday March 17th", location: "Cherokee County Magistrate Court"}',
	"2014_moco_shootings":'{subject: "Stone", action: "shoots", object: "his former sister-in-law, her husband, niece and nephew", time: " December 15, 3:30 a.m", location: "inside a home in Souderton"}	{subject: "Stone", action: "shoots", object: "his ex-wife", time: " December 15, 4:45 a.m", location: "in her apartment in Lower Salford Township"}	{subject: "Police", action: "seige", object: "Stone\'s supposed residence", time: " December 15, afternoon", location: "a home in Pennsburg"}	{subject: "Carjacking victim", action: "shoots at", object: "stone", time: " December 15, 8:00pm", location: "Doylestown"}	{subject: "Police", action: "search", object: "in and around Pennsburg", time: " December 16", location: "Pennsburg"}	{subject: "Stone", action: "found", object: "dead", time: " December 16", location: "a wooded area located half a mile from his home in Pennsburg"}',									
    "2021_fedex_shooting":	'{subject: "Hole", action: "drove to", object: "fedex facility", time: "  April 15, 2021", location: "Indianapolis, Indiana"}	{subject: "Hole", action: "fires at", object: "fedex employees", time: "  April 15, 2021", location: "Indianapolis Fedex Facility Parking Lot"}	{subject: "Hole", action: "shoots", object: "himself", time: "  April 15, 2021", location: "Indianapolis Fedex Facility"}	{subject: "Officers", action: "respond to", object: "shooting", time: "  April 15, 2021", location: "Indianapolis Fedex Facility Parking Lot"}',																	
    "2022_fbi_attack": '{subject: "FBI", action: "execute", object: "search warrant", time: "August 8, 2022", location: "Mar-a-Lago"}	{subject: "Shiffer ", action: "attempts to breach", object: "FBI field office", time: "August 11, 2022, 9:15 A.M.", location: "FBI\'s Cincinnati field office in Kenwood, Ohio"}	{subject: "Shiffer ", action: "fires", object: "nail gun", time: "August 11, 2022, 9:15 A.M.", location: "FBI\'s Cincinnati field office in Kenwood, Ohio"}	{subject: "Shiffer ", action: "publishes", object: "incomplete post", time: "August 11, 2022, 9:29 A.M.", location: "Kenwood, Ohio"}	{subject: "Shiffer ", action: "shoots", object: "pursuing officers", time: "August 11, 2022", location: "Interstate 71, Ohio"}	{subject: "Shiffer ", action: "engages in", object: "standoff with officers", time: "August 11, 2022", location: "cornfield in Clinton County, Ohio"}	{subject: "Police", action: "attempt to arrest", object: "Shiffer", time: "August 11, 2022", location: "cornfield in Clinton County, Ohio"}	{subject: "Police", action: "shoot", object: "Shiffer", time: "August 11, 2022", location: "cornfield in Clinton County, Ohio"}',														
    "2019_jersey_shooting":	'{subject: "Police", action: "approach", object: "shooting suspects", time: "December 10, 2019", location: "Bayview Cemetery in Jersey City, New Jersey"}	{subject: "Assailants", action: "shoot and kill", object: "police officer", time: "December 10, 2019", location: "Bayview Cemetery in Jersey City, New Jersey"}	{subject: "Assailants", action: "drive to", object: "a kosher grocery store", time: "December 10, 2019", location: "JC Kosher Supermarket in the Greenville section of Jersey City"}	{subject: "Assailants", action: "open fire on", object: "a kosher grocery store", time: "December 10, 2019", location: "JC Kosher Supermarket in the Greenville section of Jersey City"}	{subject: "Assailants", action: "exchange fire with", object: "the police ", time: "December 10, 2019", location: "JC Kosher Supermarket in the Greenville section of Jersey City"}	{subject: "Armored personnel carrier", action: "rammed through", object: "storefront ", time: "December 10, 2019", location: "JC Kosher Supermarket in the Greenville section of Jersey City"}	{subject: "Police", action: "discover", object: "pipe bomb and bomb materials ", time: "December 10, 2019", location: "JC Kosher Supermarket in the Greenville section of Jersey City"}',															
    "2019_naval_shooting": '{subject: "Twitter user M7MD_SHAMRANI", action: "posts", object: "hate message", time: " December 6, 2019 6:39 a.m", location: "Pensacola, Florida"}	{subject: "suspect", action: "fired", object: "shots", time: " December 6, 2019  6:43 a.m.", location: "Pensacola, Florida"}	{subject: "victim", action: "alerts", object: " the first response team", time: " December 6, 2019", location: "Pensacola, Florida"}	{subject: "two deputies ", action: "shoot and kill", object: "suspect", time: " December 6, 2019  6:58 a.m.", location: "Pensacola, Florida"}',																		
    "2022_greenwood_shooting": '{subject: "Jonathan Sapirman", action: "walked to", object: "mall", time: " July 17, 2022 4:55 p.m.", location: "Greenwood, Indiana"}	{subject: "Jonathan Sapirman", action: "entered", object: "mall restroom", time: " July 17, 2022", location: "Greenwood, Indiana"}	{subject: "Jonathan Sapirman", action: "opened fire on", object: "mall food court", time: " July 17, 2022 5:56:48 p.m.", location: "Greenwood, Indiana"}	{subject: "Elisjsha Dicken", action: "returned fire on", object: "shooter", time: " July 17, 2022 5:57:03 p.m.", location: "Greenwood, Indiana"}	{subject: "Elisjsha Dicken", action: "alerted", object: "nearby security guards", time: " July 17, 2022", location: "Greenwood, Indiana"}',																	
    "2020_mayfair_shooting": '{subject: "Alvin Cole", action: "was killed", object: "in a shooting", time: "February 2, 2020", location: "Mayfair Mall"}	{subject: "Unidentified suspect", action: "fired", object: "eight to fifteen shots", time: "around 2:50 p.m. CST on November 20, 2020", location: "entrance to the Macy\'s in the mall"}	{subject: "Seven adults and one teenager", action: "were injured", object: "in the shooting", time: "November 20, 2020", location: "Mayfair Mall"}	{subject: "Xavier Sevilla", action: "pleaded guilty", object: "to five counts of first-degree reckless injury", time: "January 6, 2023", location: "Mayfair Mall"}',																		
    "2018_gazette_shooting": '{subject: "Anne Arundel County Police Department", action: "reported", object: "shooting", time: "Around 2:34 pm (EDT) 28 June, 2018", location: "Anne Arundel County"}	{subject: "Gunman", action: "barricaded", object: "rear exit of the office", time: "Before the 2:34 pm 28 June 2018", location: "Office"}	{subject: "Gunman", action: "used", object: "12-gauge Mossberg 500 pump-action shotgun", time: "During the shooting", location: "Office"}	{subject: "Phil Davis", action: "described", object: "office as a \'war zone\'", time: "After the shooting", location: "The Capital\'s office"}	{subject: "Wendi Winters", action: "confronted/charged", object: "gunman", time: "During a pause in the shooting", location: "Office"}	{subject: "Injured victims", action: "sent", object: "Anne Arundel Medical Center", time: "After the shooting", location: "Anne Arundel County"}	{subject: "Police", action: "discovered", object: "suspect underneath a desk", time: "After the shooting", location: "Office"}',															
    "2021_kroger_shooting":	'{subject: "Gunman (Uk Thang)", action: "got into", object: "altercation with another Kroger employee", time: "7:00 a.m.", location: "Kroger grocery store, Collierville, Tennessee"}	{subject: "Gunman (Uk Thang)", action: "returned/opened fire", object: "with two pistols and a rifle", time: "1:30 p.m.", location: "Kroger grocery store, Collierville, Tennessee"}	{subject: "Authorities", action: "began receiving", object: "9-1-1 calls", time: "around 1:30 p.m.", location: "Kroger store, Collierville, Tennessee"}	{subject: "Uk Thang", action: "was identified as", object: "the shooter", time: "post-incident", location: "Collierville, Tennessee"}	{subject: "Law enforcement agencies", action: "responded/investigated", object: "the shooting scene", time: "post-incident", location: "Kroger grocery store, Collierville, Tennessee"}',																	
    "2019_kyoto_shooting": '{subject: "perpetrator", "action": "set on fire", "object": "Studio 1", "location": "Studio 1", "time": "18 July 2019 at around 13:31 am"}	{"subject": "fire", "object": "N/A", "action": "under control", "location": "Studio 1", "time": "3:19 p.m."}	{subject: "Victims", action: "attempted", object: "to escape", time: "during the fire", location: "stairs from third floor to the roof of Studio 1"}	{"subject": "fire", "action": "was extinguished", object": "N/A", "location": "Studio 1", "time": "19 July 2019 at 6:20 am"}	{"subject": "digitized original drawers", "action": "recovered", "object": "N/A", "location": "Studio 1", "time": "29 July"}',																	
    "2023_tornados"	:'{subject: "Multi-tornado outbreak", action: "began/started", object: "in Western US", time: "June 20", location: "Texas, Wyoming, Colorado, Nebraska, Oklahoma"}	{subject: "Severe storm/tornado", action: "killed/injured", object: "four people", time: "Wednesday Night", location: "Matador Texas"}	{subject: "Arkansas State Leaders", action: "declare", object: "state of emergency", time: "Monday Afternoon", location: "Little Rock, Arkansas"}	{subject: "Georgians", action: "lose", object: "power/electricity", time: "Monday Morning", location: "Atlanta, Georgia"}	{subject: "Denver Concertgoers", action: "pelted/injured", object: "hailstorm/thunderstorms", time: "Wednesday Night", location: "Denver, Colorado"}',																	
    "2023_hawaii_fires"	:'{subject: "First small fires", action: "ignited", object: "on Maui", time: "August 4", location: "Maui"}	{subject: "National Weather Service\'s office", action: "issued", object: "a red flag warning", time: "August 7", location: "Honolulu"}	{subject: "Strong winds", action: "knock down", object: "Utility Poles", time: "August 8", location: "Maui"}	{subject: "Peak wind gusts", action: "damage", object: "homes, buildings and utility poles", time: "August 8", location: "Lahaina"}	{subject: "Residents", action: "evacuate", object: "homes and residences", time: "August 8 6:37 a.m. HST", location: "Lahaina"}	{subject: "Fire", action: "crossed", object: "Honoapiilani Highway", time: "August 8 4:46 p.m. HST", location: "Lahaina"}	{subject: "Kula Fire", action: "burns down", object: "1000 acres  including residences", time: "August 9", location: "Kula"}	{subject: "Officials", action: "state", object: "sirens were not activated", time: "August 11", location: "Lahaina"}	{subject: "Residents", action: "allowed to return", object: "to residences", time: "September 25", location: "Lahaina, Pūlehu-Kīhei"}',													
    "2021_kentucky_tornado"	:'{subject: "Violent EF4 tornado", action: "moved", object: "across Western Kentucky", time: "late evening of Friday, December 10, 2021", location: "Mayfield, Princeton, Dawson Springs, Bremen"}	{subject: "Storm Prediction Center (SPC)", action: "outlined", object: "a slight risk of severe weather", time: "On December 8", location: "Mississippi Valley"}	{subject: "Intense upper-level trough", action: "progressed", object: "across the High Plains", time: "morning of December 10", location: "Mississippi Valley"}	{subject: "Supercell", action: "spawned", object: "a tornado family", time: "during the outbreak", location: "from eastern Arkansas to northeastern Kentucky"}	{subject: "Tornado", action: "began", object: "in the community of Woodland Mills", time: "8:54 p.m. CST (02:54 UTC)", location: "Obion County, Tennessee"}	{subject: "Tornado", action: "entered", object: "Mayfield", time: "9:26 p.m. CST (03:26 UTC)", location: "Mayfield, Kentucky"}	{subject: "National Weather Service", action: "issued", object: "a tornado emergency", time: "9:26 p.m. CST (03:26 UTC)", location: "for Mayfield"}	{subject: "Tornado", action: "hit", object: "city of Dawson Springs", time: "not specified", location: "Caldwell–Hopkins county line"}	{subject: "Researchers Timothy Marshall, Zachary B. Wienhoff, Christine L. Wielgos, and Brian E. Smith", action: "published", object: "a damage survey", time: "2022", location: "through Mayfield and Dawson Springs"}',													
    "2021_eruption"	:'{subject: "La Soufrière", action: "erupted explosively", object: null, time: "9 April 2021", location: "Saint Vincent"}	{subject: "Inhabitants of the island", action: "evacuated", object: null, time: "April 2021", location: "Saint Vincent"}	{subject: "Services", action: "were affected", object: "electricity and water", time: "April 2021", location: "Saint Vincent"}	{subject: "Explosive eruption", action: "occurred", object: "with an ash plume", time: "9 April 2021", location: "Saint Vincent"}	{subject: "Countries and organizations", action: "provided", object: "relief and support", time: "April 2021", location: "Saint Vincent"}	{subject: "Eruptions", action: "ended", object: null, time: "22 April", location: "Saint Vincent"}',																
    "2017_mocoa_landslide":'{subject: "Heavy rain", action: "triggered", object: "flash flooding and landslides", time: "pre-dawn hours of 1 April 2017", location: "Mocoa, Putumayo, Colombia"}	{subject: "Mesoscale convective complex", action: "developed", object: "heavy rainfall", time: "31 March 2017 evening", location: "southern Colombia"}	{subject: "Rivers (Mocoa, Sangoyaco and Mulato)", action: "overflowed", object: "mudflows", time: "3:00 a.m.", location: "Mocoa"}	{subject: "Mocoa\'s neighborhoods", action: "affected/destroyed", object: "by the disaster", time: "After the landslides", location: "Mocoa, Putumayo, Colombia"}	{subject: "President Juan Manuel Santos", action: "declared", object: "a state of emergency", time: "After the disaster", location: "Colombia"}	{subject: "Colombian Red Cross", action: "activated/deployed", object: "National Crisis Room and a team of 47 people", time: "After the disaster", location: "Mocoa, Putumayo, Colombia"}	{subject: "Médecins Sans Frontières", action: "deployed", object: "an assessment team", time: "2 April", location: "affected area"}',															
    "2010_haiti_earthquake":'{subject: "2010 Haiti earthquake", action: "struck", object: "Haiti", time: "16:53 local time (21:53 UTC) on Tuesday, 12 January 2010", location: "near the town of Léogâne, Ouest department, approximately 25 kilometres (16 mi) west of Port-au-Prince, Haiti\'s capital."}	{subject: "Aftershocks", action: "occurred", object: "post earthquake", time: "by 24 January", location: "Haiti"}	{subject: "Landmark buildings", action: "damaged/destroyed", object: "Presidential Palace, National Assembly building, Port-au-Prince Cathedral, main jail", time: "During earthquake", location: "Port-au-Prince and other cities"}	{subject: "UN Stabilization Mission headquarters (MINUSTAH)", action: "collapsed", object: "killing many including Mission\'s Chief, Hédi Annabi", time: "During earthquake", location: "Port-au-Prince"}	{subject: "Countries", action: "responded", object: "with humanitarian aid, medical teams, engineers", time: "After the earthquake", location: "Worldwide to Haiti"}	{subject: "Morgues", action: "overwhelmed", object: "by the number of bodies", time: "Immediately after the earthquake", location: "Port-au-Prince"}	{subject: "Looting and violence", action: "reported", object: "amid the chaos", time: "Days following the earthquake", location: "Port-au-Prince"}	{subject: "Relief efforts", action: "hampered", object: "due to damaged infrastructure and communication challenges", time: "Days to weeks post-earthquake", location: "Haiti"}	{subject: "underwater landslide", action: "casued", object: "localised tsunami", time: "two weeks later", location: "beach of the small fishing town of Petit Paradis"}',													
    "2021_henan_floods"	:'{subject: "Henan Province", action: "experienced", object: "flooding", time: "between 17 and 31 July 2021", location: "China"}	{subject: "Zhengzhou", action: "recorded", object: "201.9 millimetres of rainfall within an hour", time: "July 20", location: "Henan Province, China"}	{subject: "Provincial authorities", action: "reported", object: "302 deaths and over 50 missing people", time: "2 August 2021", location: "Henan Province"}	{subject: "Government investigations", action: "concluded", object: "full death toll was 398", time: "Later after 2 August 2021", location: "Henan Province"}	{subject: "Flooding", action: "left", object: "398 people dead or missing", time: "After 20 July 2021", location: "Zhengzhou, Henan Province"}',																	
    "2019_nyonoksa"	:'{subject: "Russia", action: "conducted", object: "tests of the 9M730 Burevestnik nuclear-powered cruise missile", time: "Between November 2017 and 26 February 2018", location: "Russia"}	{subject: "Accident", action: "occurred", object: "rocket engine explosion", time: "", location: "State Central Navy Testing Range (Nyonoksa)"}	{subject: "Fishermen", action: "witnessed", object: "accident", time: "8 August", location: "near the explosion site"}	{subject: "Victims", action: "treated", object: "radiation exposure", time: "8 August", location: "Semashko Medical Center in Arkhangelsk and Arkhangelsk Regional Clinical Hospital"}	{subject: "Radiation levels", action: "peaked", object: "4–16 times normal levels", time: "shortly after the explosion", location: "Severodvinsk"}	{subject: "Nyonoksa village inhabitants", action: "evacuated/canceled", object: "due to military activities", time: "14 August", location: "Nyonoksa village"}	{subject: "Russia", action: "confirmed", object: "involvement of radioactive materials", time: "After 8 August 2019", location: "Nyonoksa"}',															
    "2022_na_winter":'{subject: "North American winter storm", action: "formed", object: "wintry precipitation", time: "January 14–17, 2022", location: "eastern North America and parts of Canada"}	{subject: "Several states", action: "declared", object: "states of emergencies", time: "ahead of the storm", location: "Southeast including North Carolina, South Carolina, Georgia, and Virginia"}	{subject: "System", action: "spawned", object: "seven tornadoes", time: "during the storm", location: "Florida"}	{subject: "Winter Storm Izzy", action: "dropped", object: "snowfall", time: "during the storm", location: "High Plains and Central United States"}	{subject: "Winter storm", action: "developed", object: "low pressure", time: "January 13", location: "southwestern Canada"}	{subject: "Canada and United States", action: "prepared", object: "emergency measures and warnings", time: "ahead of the storm", location: "across Southern Ontario, Quebec, Central and Eastern United States"}	{subject: "Winter storm", action: "caused", object: "heavy snow and disruptions", time: "January 17 and 18", location: "Ontario, Canada"}	{subject: "Snowfall", action: "impacted", object: "various areas", time: "during the storm", location: "High Plains, Midwest, Southeast, Florida, and Northeast of the US"}',														
    "2011_fukushima":'{subject: "9.0 MW earthquake", action: "struck", object: "Fukushima Daiichi Nuclear Power Plant", time: "14:46, 11 March 2011", location: "Off the east coast of the Tōhoku region"}	{subject: "Power plant", action: "failed", object: "to cool reactors after shutdown", time: "Shortly after March 11, 2011", location: "Fukushima Daiichi nuclear power plant"}	{subject: "Tsunami wave", action: "hit", object: "power station", time: "50 minutes after earthquake", location: "Fukushima Daiichi"}	{subject: "Fukushima nuclear accident", action: "began", object: "at the Fukushima Daiichi nuclear power plant", time: "March 11, 2011", location: "Ōkuma, Fukushima, Japan"}	{subject: "Accident", action: "was rated", object: "seven on the INES", time: "Post-accident", location: "Fukushima, Japan"}	{subject: "164,000 residents", action: "were displaced", object: "permanently or temporarily", time: "After the accident", location: "Surrounding area of Fukushima"}	{subject: "Investigations", action: "faulted", object: "lapses in safety and oversight", time: "After the accident", location: "Fukushima, Japan"}	{subject: "Radioactive materials", action: "released", object: "into atmosphere and ocean", time: "Post-disaster", location: "Fukushima Daiichi"}',														
    "2020_kyrgyz":'{subject: "Protestors", action: "attack", object: "Police", time: "October 5th", location: "Bishkek, Kyrgyzstan"}	{subject: "Protestors", action: "seize", object: "Ala-Too square, capitol building and supreme council buildings", time: "October 6th Morning", location: "Bishkek, Kyrgyzstan"}	{subject: "Electors", action: "annul", object: "parliamentary elections", time: "October 6th", location: "Kyrgyzstan"}	{subject: "Protestors", action: "free", object: "former president Almazbek Atambayev and opposition politician Sadyr Japarov", time: "October 6th", location: "Kyrgyzstan"}	{subject: "Protestors", action: "protest", object: "nomination of Japarov", time: "October 7th", location: "Kyrgyzstan"}	{subject: "Jeenbekov ", action: "declares", object: "state of emergency", time: "October 9th", location: "Bishkek, Kyrgyzstan"}	{subject: "Kyrgyzstani special forces", action: "detain", object: "former President Almazbek Atambayev", time: "October 10th", location: "Bishkek, Kyrgyzstan"}	{subject: "Jeenbekov ", action: "declares", object: "second state of emergency", time: "October 12th", location: "Bishkek, Kyrgyzstan"}	{subject: "Kanat Isaev", action: "elected", object: "as the new Speaker of the Supreme Council", time: "October 13th", location: "Bishkek, Kyrgyzstan"}	{subject: "Jeenbekov ", action: "resigns", object: "as President of Kyrgyzstan", time: "October 15th", location: "Bishkek, Kyrgyzstan"}',												
    "2019_legislative_hk":'{subject: "Activists", action: "headed", object: "towards the Legislative Council Complex", time: "1 July 2019", location: "Hong Kong"}	{subject: "Protesters", action: "stormed", object: "the Legislative Council Complex", time: "around 9:00 pm", location: "Hong Kong"}	{subject: "Protesters", action: "damaged/defaced", object: "portraits, furniture, emblem, etc.", time: "1 July 2019", location: "Legislative Council Complex"}	{subject: "Police", action: "started using", object: "tear gas to disperse protesters", time: "12:05 am 2 July", location: "around the Legislative Council complex"}	{subject: "Police", action: "arrested", object: "individuals in connection with the incident", time: "between 3 July and 5 July", location: "Hong Kong"}',												
    "2019_hkpoly_siege":'{subject: "Citizens", action: "attempted to clear", object: "roadblocks", time: "10:00 am on 17 November", location: "Austin Road and Chatham Road South, near Rosary Church"}	{subject: "Riot police", action: "arrived and confronted", object: "protesters", time: "around 11:00 am on 17 November", location: "Austin Road and Chatham Road South, near Rosary Church"}	{subject: "Police", action: "announced", object: "arrest criteria", time: "9:00 pm on 17 November", location: "Polytechnic University"}	{subject: "Protesters", action: "damaged and stole", object: "chemicals from laboratories", time: "17 November", location: "Polytechnic University"}	{subject: "Pro-democracy legislators", action: "requested meeting", object: "HKPF commander", time: "18 November", location: "Hong Kong"}	{subject: "Riot police", action: "fired tear gas", object: "towards Queen Elizabeth Hospital", time: "11:00 am on 18 November", location: "Queen Elizabeth Hospital"}	{subject: "Riot police", action: "trapped", object: "protesters", time: "19-27 November", location: "inside Polytechnic University"}	{subject: "Police", action: "lifted the cordon", object: "after searching", time: "28-29 November", location: "Polytechnic University"}',									
    "2017_zimbabwea_coup":'{subject: "Military armoured vehicles", action: "spotted", object: "on roadways", time: "Tuesday, 14 November", location: "Harare, Zimbabwe"}	{subject: "Soldiers", action: "took over", object: "ZBC offices", time: "Tuesday evening, 14 November", location: "Harare"}	{subject: "Army", action: "raided", object: "homes of officials", time: "Wednesday, 15 November", location: "Harare and surrounding"}	{subject: "Major General Sibusiso Moyo", action: "spoke", object: "on ZBC", time: "5 am, Wednesday, 15 November", location: "Harare"}	{subject: "Military", action: "apprehended", object: "Ignatius Chombo", time: "Wednesday morning, 15 November", location: "Harare"}	{subject: "Morgan Tsvangirai", action: "returned & called for", object: "Mugabe to step down", time: "After Wednesday, 15 November", location: "Zimbabwe"}	{subject: "Citizens", action: "demonstrated", object: "supporting army & against Mugabe", time: "Saturday, 18 November", location: "Harare and major towns in Zimbabwe"}	{subject: "Robert Mugabe", action: "resigned", object: "from presidency", time: "18:00, Tuesday, 21 November", location: "Zimbabwe"}',									
    "2018_italian_gov":'{subject: "President Mattarella", action: "held", object: "another round of consultation", time: "between 11 and 12 April 2018", location: "Italy"}	{subject: "Elisabetta Casellati", action: "was given the task", object: "to reconcile issues", time: "18 April 2018", location: "Italy"}	{subject: "Roberto Fico", action: "was given", object: "an exploratory mandate", time: "23 April 2018", location: "Italy"}	{subject: "Giuseppe Conte", action: "was proposed", object: "as Prime Minister", time: "21 May", location: "Italy"}	{subject: "Giuseppe Conte", action: "gave up", object: "on forming a government", time: "27 May", location: "Italy"}	{subject: "Carlo Cottarelli", action: "was called", object: "for the task of forming a new government", time: "28 May", location: "Italy"}',											
    "2018_thai_cave":'{subject: "Vern Unsworth", action: "advise", object: "Thai government", time: "24 June", location: "Tham Luang cave"}	{subject: "Thai Navy SEALs divers", action: "begin searching", object: "the cave", time: "25 June", location: "Tham Luang cave"}	{subject: "US Air Force team & Australian Federal Police", action: "joined", object: "rescue efforts", time: "28-29 June", location: "Tham Luang cave"}	{subject: "BCRC divers Richard Stanton and John Volanthen", action: "discovered", object: "the twelve boys and the coach", time: "2 July", location: "Tham Luang cave"}	{subject: "Thai Navy SEALs", action: "joined", object: "trapped group", time: "3 July", location: "Tham Luang cave"}	{subject: "Rescue divers", action: "plan", object: "retrieve boys with diving", time: "Shortly before 8 July", location: "Tham Luang cave"}	{subject: "Saman Kunan", action: "died", object: "during a dive", time: "5 July", location: "Tham Luang cave"}	{subject: "Rescue team", action: "initiated extraction", object: "of boys and coach", time: "8 July", location: "Tham Luang cave"}	{subject: "Rescuers", action: "completed extraction", object: "all boys and coach", time: "10 July", location: "Tham Luang cave"}',								
    "2018_armenian_revolution":'{subject: "Protesters", action: "intended to block", object: "entrances to the National Assembly", time: "April 17", location: "National Assembly building"}	{subject: "Nikol Pashinyan", action: "met", object: "prime minister", time: "10 am on April 22", location: "Republic Square"}	{subject: "Nikol Pashinyan", action: "was detained", object: "by riot police", time: "post-meeting", location: "Erebuni district"}	{subject: "Protesters", action: "resumed", object: "demonstrations", time: "April 23", location: "Yerevan"}	{subject: "Nikol Pashinyan", action: "called for", object: "renewed protests", time: "April 25", location: "Yerevan"}	{subject: "Tens of thousands", action: "continued to protest", object: "Pashinyan\'s leadership", time: "April 26", location: "Yerevan"}	{subject: "Nikol Pashinyan", action: "called on", object: "supporters to suspend their rallies", time: "April 27", location: "Yerevan"}	{subject: "Parliament", action: "held elections", object: "for a new Prime Minister", time: "May 1", location: "Republic Square"}	{subject: "Nation", action: "ground to a halt", object: "due to strikes and blockages", time: "May 2", location: "Throughout the nation"}	{subject: "Nikol Pashinyan", action: "was elected", object: "as the new Prime Minister", time: "May 8", location: "Parliament"}',							
    "2017_lebsaudi_dispute":'{subject: "Lebanese prime minister Saad Hariri", action: "tendered", object: "his resignation", time: "4 November 2017", location: "Saudi Arabia"}	{subject: "Saad Hariri", action: "declared", object: "suspension of his resignation", time: "21 November", location: "Beirut"}	{subject: "Saudi Arabia", action: "intercepted", object: "a ballistic missile", time: "4 November 2017", location: "Saudi Arabia"}	{subject: "Hezbollah leader Hassan Nasrallah", action: "said", object: "Saudi Arabia had declared war", time: "9 November 2017", location: "Lebanon"}	{subject: "Saudi Arabia, UAE, Kuwait", action: "urged", object: "their citizens to leave Lebanon", time: "9 November 2017", location: "Lebanon"}	{subject: "French President Emmanuel Macron", action: "made", object: "an unscheduled visit", time: "10 November 2017", location: "Saudi Arabia"}	{subject: "French President Macron", action: "invited", object: "Saad Hariri and his family", time: "16 November 2017", location: "France"}',										
    "2013_tunisian_crisis":'{subject: "Democratic Patriots\' Movement leader Chokri Belaid", action: "was assassinated", object: "", time: "6 February 2013", location: "Tunis"}	{subject: "People\'s Movement leader Mohamed Brahmi", action: "was assassinated", object: "", time: "25 July 2013", location: "Tunis"}	{subject: "Chokri Belaid", action: "was leaving", object: "his house", time: "6 February 2013", location: "Tunisian General Labour Union headquarters"}	{subject: "Mohamed Brahmi", action: "was shot dead", object: "", time: "25 July 2013", location: "in front of his home in Tunis"}	{subject: "Tunisian Prosecutor", action: "made a statement", object: "about the autopsy of Brahmi\'s corpse", time: "after the assassination", location: "Tunisia"}	{subject: "Tunisia\'s interior minister", action: "announced", object: "the same weapon killed Belaid and Brahmi", time: "after the assassinations", location: "Tunisia"}	{subject: "Tens of thousands of protesters", action: "rallied", object: "", time: "6 August 2013", location: "Tunis"}',										
    "2021_capitol_attack":'{subject: "Trump", action: "encouraging", object: "protesters", time: "January 6th morning", location: "Washington D.C rally"}	{subject: "Capitol Police", action: "respond", object: "threats and pipe bomb reports", time: "January 6th noon", location: "Capitol Hill"}	{subject: "rioters", action: "overrun, breach", object: "Capitol Building", time: "January 6th afternoon", location: "Capitol Building"}	{subject: "National Guard", action: "clear out, enforce", object: "Capitol, curfew", time: "January 6th late afternoon", location: "Capitol Hill"}	{subject: "Congress", action: "reconvenes, retains", object: "electoral college vote", time: "January 6th late evening", location: "House/Senate Chambers in Capitol Building"}',												
}


def main(args):

    os.environ["CUDA_VISIBLE_DEVICES"] = str(args.gpu)

    if not os.path.exists(args.output_dir):
        os.makedirs(args.output_dir)

    if (args.title is not None) and (args.theme is not None):
        titles = [args.title]
        themes = [args.theme]
    else:
        titles = ["2021_atlanta_shootings", "2014_moco_shootings", "2021_fedex_shooting", "2022_fbi_attack", "2019_jersey_shooting", "2019_naval_shooting", "2022_greenwood_shooting", "2020_mayfair_shooting",
              "2018_gazette_shooting", "2021_kroger_shooting", "2019_kyoto_shooting", "2023_tornados", "2023_hawaii_fires", "2021_kentucky_tornado", 
              "2021_eruption", "2017_mocoa_landslide", "2010_haiti_earthquake", "2021_henan_floods", "2019_nyonoksa", "2022_na_winter", "2011_fukushima",
              "2020_kyrgyz", "2019_legislative_hk", "2019_hkpoly_siege", "2017_zimbabwea_coup", "2018_italian_gov", "2018_thai_cave", "2018_armenian_revolution", 
              "2017_lebsaudi_dispute", "2013_tunisian_crisis", "2021_capitol_attack"]
        themes = ["terrorism", "terrorism", "terrorism", "terrorism", "terrorism", "terrorism", "terrorism", "terrorism", "terrorism", "terrorism", "terrorism", "natural_disasters", "natural_disasters", "natural_disasters", "natural_disasters", "natural_disasters", 
                "natural_disasters", "natural_disasters", "natural_disasters", "natural_disasters", "natural_disasters", "politics", "politics", "politics", "politics", "politics", "politics", "politics", "politics", "politics", "politics"]
            

    assert len(titles) == len(themes)

    mean_total = None
    
    for title, theme in tqdm(zip(titles, themes), total=len(titles)):
        args.theme = theme
        args.title = title
        args.num = len(gold_episodes[args.title].split("\t"))
        print("CURRENT:", args.theme, args.title, args.num)



        all_ev_id = set()
        gt = {}
        with open(os.path.join('groundtruth', f'{args.title}_groundtruth.txt'), encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line == '': continue
                ev_id, text = line.split('\t')
                gt[text] = ev_id
                all_ev_id.add(ev_id)

        with open(os.path.join('final_output', f'{args.title}_finaloutput.txt'), "w") as f:
            e_id = 0
            for c in clusters:
                f.write(f"Episode #{e_id}:\n")
                for s in c:
                    if s[1] in gt:
                        f.write(f'{gt[s[1]]}\t{s}\n')
                e_id += 1
                f.write("\n\n")
            f.write(f'FINAL RESULTS for {args.theme}-{args.title}:\n{prec}\n{recall}\n{f1}')


        # create output subdirectories if they do not exist
        if not os.path.exists(f"{args.output_dir}/{args.theme}/"):
            os.makedirs(f"{args.output_dir}/{args.theme}/")
        if not os.path.exists(f"{args.output_dir}/{args.theme}/{args.title}/"):
            os.makedirs(f"{args.output_dir}/{args.theme}/{args.title}/")
        
        episodes, clusters, mean_score, max_score = epimine.main(args)
        

        if mean_score is None:
            print(f"{args.title} under theme {args.theme} failed! Moving forward.")
        else:
            if mean_total is None:
                mean_total = mean_score
            else:
                mean_total = np.concatenate((mean_total, mean_score), axis=0)
            
            all_ev_id = set()
            gt = {}
            with open(os.path.join('groundtruth', f'{args.title}_groundtruth.txt'), encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if line == '': continue
                    ev_id, text = line.split('\t')
                    gt[text] = ev_id
                    all_ev_id.add(ev_id)
            
            with open(os.path.join('final_output', f'{args.title}_finaloutput.txt'), "w") as f:
                e_id = 0
                f.write(f"{episodes}\n")
                for c in clusters:
                    f.write(f"Episode #{e_id}:\n")
                    for s in c:
                        if s[1] in gt:
                            f.write(f'{gt[s[1]]}\t{s}\n')
                    e_id += 1
                    f.write("\n")
                f.write(f'Final Mean Score: {mean_score}\n')
                f.write(f'Final Max Score: {max_score}')
    
    print("FINAL THEME STATS:", np.mean(mean_total, axis=0))
    

if __name__ == '__main__':
    class Args():
        def __init__(self):
            self.theme = None
            self.title = None
            self.gpu = 0
            self.output_dir = "final_output"
            self.lm_type = 'bbu'
            self.layer = 12
            self.vocab_min_occurrence = 1
            self.doc_thresh = 0.25
            self.emb_dim = 768 # default
            self.batch_size = 32
            self.trials = 10
            self.api_key = "[ANTHROPIC API KEY]"

            # eval
            self.eval_top = 5
            self.num = 5
    
    args = Args()
    main(args)